### ISSUE TITLE
transformar is_valid_point em condição prévia à create_sentences

### ISSUE THREAD

**Issue by fernandysson** [michaeloc/its_research#3]
https://github.com/michaeloc/its_research/blob/1aa8a1ce3d24e800b6419e2b00f967a4cb2331ba/building_trajectories/sentences.py#L81-L82

Pensei em iterar sobre o conjunto de trajetórias candidatas e a partir delas criar as sentenças. Na prática estamos trazendo uma parte do is_valid_point para um ponto prévio ao create_sentences. Só resta perguntar se os pontos subsequentes estão dentro da janela temporal.

**Comment by michaeloc** [comment]
Então, a diferença temporal entre dois pintos consecutivos de deve ser <= a um valor, no caso eu estava adotando 5 min, não sei pq alterei o método para Segundos! Em resumo essa janela devs ser threshold configurável, hj colocamos 5 min, mas talvez em outro momento podemos usar outro limiar! Acho que isso pode ser passado como parâmetro

**Comment by fernandysson** [comment]
Pelo que vi aqui existem 3 condições básicas para um trajetória ser válida.

1. todos os seus pontos pertencem a uma mesma chave única, no caso esta chave é uma tupla que pode ser diferente para cada dataset. Puxei para dentro do PreProcess a função de encontrar quantas trajetórias únicas podem existir (teto). 
2. para cada par de pontos consecutivos deve haver uma janela de no máximo X segundos. Esta verificação é parte do create_sentences
3. uma trajetória de no mínimo Y pontos. Esta definição também está na classe PreProcess e fiz a retirada prévia de trajetórias que não contém Y pontos, assim o create_sentences não precisa verificar, poupando algum tempo.

**Comment by fernandysson** [comment]
eu to chamando o create_sentences de dentro de um FOR, assim eu só verifico uma potencial trajetória por vez e agrego à lista de trajetórias.
Esse processamento é completamente independente e poderia ser paralelizado. No caso cada loop do FOR. 

Tentei com essa biblioteca joblib, mas não finalizou. Deixei rodando linearmente e depois voltarei para implementar a paralelização.
```
from joblib import Parallel, delayed
query = "(line_id == {}) & (journey_id == '{}') & (time_frame == '{}')  & (vehicle_journey_id == '{}') & (operator == '{}') & (vehicle_id == {})"
complete = Parallel(n_jobs=-1)(delayed
                               (sentence.create_sentences)
                                   (data_merged.query(query.format(*chave)))
                                       for chave in sentence.trejectories)
```

**Comment by fernandysson** [comment]
Consegui fazer com o Spark.
Fiquei confuso pq nao funcionou chamar a classe pelo Jupyter, mas qnd puxo as funções para o Notebook ou quando rodo o IPython na pasta base da função flui normal.

**Comment by fernandysson** [comment]
Eu particionei antes os dataFrames baseado na chave que é a tupla de valores que torna uma trajatória única. E só mantive os que têm um número mínimo de pontos, no caso 50.
```
dfs = [x for _,x in data_merged.groupby(trajetoria) if (len(x) > 50)]
```
Depois distribui eles com o Spark e mandei a função create_sentences para os nós.
```
A=sc.parallelize(dfs)
B = A.map(lambda x: create_sentences(x, trajetoria))
```
Não consegui rodar o collect creio por limitação da minha maquina. Vou subir tudo no git e tentar rodar na maquina lá do CIn.
