### ISSUE TITLE
Tornar a Classe agnóstica quanto às features de trajetórias

### ISSUE THREAD

**Issue by fernandysson** [michaeloc/its_research#4]
https://github.com/michaeloc/its_research/blob/1aa8a1ce3d24e800b6419e2b00f967a4cb2331ba/building_trajectories/sentences.py#L18

https://github.com/michaeloc/its_research/blob/1aa8a1ce3d24e800b6419e2b00f967a4cb2331ba/building_trajectories/sentences.py#L40-L46

Reorganizei a Classe para receber um array com as features que dão unicidade à trajetória.

**Comment by michaeloc** [comment]
Blz! Ainda não tive como testar
